pub mod cleanup;
pub mod engine;
pub mod runner;
pub mod store;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum JobKind {
    Custom,
    Region,
}

impl JobKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Custom => "custom",
            Self::Region => "region",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum JobStatus {
    Queued,
    Running,
    Done,
    Failed,
    Expired,
}

impl JobStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Queued => "queued",
            Self::Running => "running",
            Self::Done => "done",
            Self::Failed => "failed",
            Self::Expired => "expired",
        }
    }
}

/// One extract job. Region jobs use the region id as the job id so a region
/// is only ever generated once at a time.
#[derive(Debug, Clone)]
pub struct Job {
    pub id: String,
    pub kind: JobKind,
    pub status: JobStatus,
    /// Display name; custom exports always have one (user-provided or generated).
    pub name: Option<String>,
    pub client_ip: Option<String>,
    pub region_id: Option<String>,
    /// GeoJSON geometry (Polygon or MultiPolygon) the extract is cut to.
    pub geometry: String,
    pub maxzoom: u8,
    pub estimated_tiles: u64,
    pub file_path: Option<String>,
    pub file_size: Option<u64>,
    pub error: Option<String>,
    pub pinned: bool,
    pub created_at: DateTime<Utc>,
    pub started_at: Option<DateTime<Utc>>,
    pub finished_at: Option<DateTime<Utc>>,
    pub expires_at: Option<DateTime<Utc>>,
    pub last_download_at: Option<DateTime<Utc>>,
}

impl Job {
    /// A freshly queued custom export job.
    pub fn new_custom(
        name: String,
        geometry: String,
        maxzoom: u8,
        estimated_tiles: u64,
        client_ip: String,
    ) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            kind: JobKind::Custom,
            status: JobStatus::Queued,
            name: Some(name),
            client_ip: Some(client_ip),
            region_id: None,
            geometry,
            maxzoom,
            estimated_tiles,
            file_path: None,
            file_size: None,
            error: None,
            pinned: false,
            created_at: Utc::now(),
            started_at: None,
            finished_at: None,
            expires_at: None,
            last_download_at: None,
        }
    }

    /// A freshly queued region extract job (id = region id).
    pub fn new_region(region_id: String, geometry: String, maxzoom: u8, pinned: bool) -> Self {
        Self {
            id: region_id.clone(),
            kind: JobKind::Region,
            status: JobStatus::Queued,
            name: None,
            client_ip: None,
            region_id: Some(region_id),
            geometry,
            maxzoom,
            estimated_tiles: 0,
            file_path: None,
            file_size: None,
            error: None,
            pinned,
            created_at: Utc::now(),
            started_at: None,
            finished_at: None,
            expires_at: None,
            last_download_at: None,
        }
    }

    pub fn is_active(&self) -> bool {
        matches!(self.status, JobStatus::Queued | JobStatus::Running)
    }
}

/// Field updates applied together with a status transition.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct StatusDetail {
    pub error: Option<String>,
    pub file_path: Option<String>,
    pub file_size: Option<u64>,
    pub started_at: Option<DateTime<Utc>>,
    pub finished_at: Option<DateTime<Utc>>,
    pub expires_at: Option<DateTime<Utc>>,
}

const NAME_MAX_CHARS: usize = 40;

const NAME_ADJECTIVES: [&str; 16] = [
    "amber", "brisk", "cedar", "dusky", "eager", "flint", "golden", "hazel", "indigo", "jade",
    "keen", "lunar", "mossy", "north", "ochre", "pale",
];

const NAME_NOUNS: [&str; 16] = [
    "atlas", "basin", "cliff", "delta", "estuary", "fjord", "glacier", "harbour", "island",
    "jetty", "knoll", "lagoon", "meadow", "outcrop", "plateau", "ridge",
];

/// A readable autogenerated export name, e.g. "brisk-lagoon-4f".
pub fn generate_export_name() -> String {
    let id = uuid::Uuid::new_v4();
    let bytes = id.as_bytes();
    let adjective = NAME_ADJECTIVES[bytes[0] as usize % NAME_ADJECTIVES.len()];
    let noun = NAME_NOUNS[bytes[1] as usize % NAME_NOUNS.len()];
    format!("{adjective}-{noun}-{:02x}", bytes[2])
}

/// Validate an optional user-supplied export name; empty means autogenerate.
pub fn normalise_export_name(input: Option<&str>) -> Result<String, String> {
    let trimmed = input.unwrap_or("").trim();
    if trimmed.is_empty() {
        return Ok(generate_export_name());
    }
    if trimmed.chars().count() > NAME_MAX_CHARS {
        return Err(format!("name must be at most {NAME_MAX_CHARS} characters"));
    }
    let valid = trimmed
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, ' ' | '-' | '_'));
    if !valid {
        return Err("name may only contain letters, digits, spaces, dashes and underscores".into());
    }
    Ok(trimmed.to_string())
}

/// Filesystem/header-safe form of a job's display name for download filenames.
pub fn filename_for(job: &Job) -> String {
    let stem = job
        .name
        .as_deref()
        .unwrap_or(&job.id)
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect::<String>();
    format!("{}.pmtiles", stem.trim_matches('-'))
}

#[cfg(test)]
mod name_tests {
    use super::*;

    #[test]
    fn empty_input_generates_a_name() {
        let name = normalise_export_name(None).expect("generated");
        assert!(name.contains('-'));
        assert!(
            normalise_export_name(Some("  "))
                .expect("generated")
                .contains('-')
        );
    }

    #[test]
    fn valid_names_pass_through_trimmed() {
        assert_eq!(
            normalise_export_name(Some("  My London Extract ")).expect("valid"),
            "My London Extract"
        );
    }

    #[test]
    fn invalid_names_rejected() {
        assert!(normalise_export_name(Some("a/b")).is_err());
        assert!(normalise_export_name(Some(&"x".repeat(41))).is_err());
    }

    #[test]
    fn filenames_are_sanitised() {
        let mut job = Job::new_custom("My London Extract".into(), "{}".into(), 10, 1, "ip".into());
        assert_eq!(filename_for(&job), "My-London-Extract.pmtiles");
        job.name = None;
        assert!(filename_for(&job).ends_with(".pmtiles"));
    }
}
