import { expect, test } from '@playwright/test'
import { createExportViaDraw } from './helpers'

test('drawing an area produces an estimate and a named job', async ({ page }) => {
  await page.goto('/')

  await page.getByRole('button', { name: 'Custom export' }).click()
  // The public-output warning must sit next to the name field.
  await expect(page.getByText(/publicly downloadable/)).toBeVisible()

  await createExportViaDraw(page, 'my test area')
  await page.screenshot({ path: 'test-results/export-submitted.png' })

  await page.getByRole('button', { name: /Jobs/ }).click()
  const job = page.locator('article', { hasText: 'my test area' })
  await expect(job).toBeVisible()
  await expect(job.getByRole('link', { name: 'Download' })).toBeVisible({ timeout: 10_000 })
  await page.screenshot({ path: 'test-results/export-done.png' })
})

test('an omitted name is autogenerated', async ({ page }) => {
  await page.goto('/')
  await createExportViaDraw(page)

  await page.getByRole('button', { name: /Jobs/ }).click()
  // Mock autogenerates names like the backend does.
  await expect(page.locator('article .name')).not.toHaveText('')
})

test('jobs persist across a reload', async ({ page }) => {
  await page.goto('/')
  await createExportViaDraw(page, 'survives reload')

  await page.getByRole('button', { name: /Jobs/ }).click()
  await expect(page.getByText('survives reload')).toBeVisible()

  await page.reload()
  await page.getByRole('button', { name: /Jobs/ }).click()
  await expect(page.getByText('survives reload')).toBeVisible()
  await page.screenshot({ path: 'test-results/jobs-persisted.png' })
})
